spring.application.name=ClinicaDefinitiva
spring.datasource.url=jdbc:mysql://localhost:3306/prueva
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.validator=DEBUG
edad.minima.odontologo=25
edad.minima.secretario=18
edad.minima.responsable=21
security.maxAttempts=5
security.lockDurationMinutes=15
logging.config=classpath:logback-spring.xml
# Logger principal de Spring Security
logging.level.org.springframework.security=DEBUG
# Paquetes m\u00c3\u00a1s espec\u00c3\u00adficos para filtrar autenticaci\u00c3\u00b3n y autorizaci\u00c3\u00b3n
logging.level.org.springframework.security.web.authentication=TRACE
logging.level.org.springframework.security.config=DEBUG