package com.example.ClinicaDefinitiva.Enum;

public enum Permisos {


    // HORARIO

    GET_HORARIO_ID,
    GET_HORARIOS_LIST,
    GET_HORARIO_POR_ODONTOLOGO_ID,
    GET_HORARIOS_DISPONIBLE,
    GET_HORARIO_POR_FECHA,
    POST_HORARIOS,
    PUT_HORARIOS,
    DELETE_HORARIO,


    // ODONTOLOGO

    GET_ODONTOLOGO_ID,
    GET_ODONTOLOGOS_LIST,
    GET_ODONTOLOGO_POR_USUARIO_ID,
    GET_ODONTOLOGO_POR_ESPECIALIDAD,
    GET_ODONTOLOGO_POR_TURNO,
    POST_ODONTOLOGOS,
    PUT_ODONTOLOGOS,
    DELETE_ODONTOLOGOS,

    // PACIENTE

    GET_PACIENTE_ID,
    GET_PACIENTES_LIST,
    GET_PACIENTE_POR_NOMBRE,
    GET_PACIENTE_POR_DOCUMENTO,
    GET_PACIENTE_POR_USUARIO,
    GET_PACIENTE_TURNO,
    POST_PACIENTES,
    PUT_PACIENTES,
    DELETE_PACIENTES,

    // RESPONSABLE

    GET_RESPONSABLE_ID,
    GET_RESPONSABLE_POR_PACIENTE,
    GET_RESPONSABLE_POR_DOCUMENTO,
    GET_RESPONSABLE_POR_TELEFONO,
    GET_RESPONSABLE_POR_PARENTESCO,
    POST_RESPONSABLES,
    PUT_RESPONSABLES_CAMBIO_TOTAL,
    PUT_RESPONSABLES,
    DELETE_RESPONSABLES,

    // SECRETARIO

    GET_SECRETARIO_ID,
    GET_SECRETARIOS_LIST,
    GET_SECRETARIO_POR_NOMBRE,
    GET_SECRETARIO_SECTOR,
    GET_SECRETARIO_POR_USUARIO,
    POST_SECRETARIOS,
    PUT_SECRETARIOS,
    DELETE_SECRETARIOS,

    // TURNO

    GET_TURNO_ID,
    GET_TURNOS_LIST,
    GET_TURNO_POR_ODONTOLOGO,
    GET_TURNO_POR_ESTADO,
    GET_TURNO_POR_DISPONIBILIDAD,
    GET_TURNO_POR_FECHA,
    POST_TURNOS,
    PUT_TURNOS,
    DELETE_TURNOS,

    // USUARIO

    GET_USUARIO_ID,
    GET_USUARIOS_LIST,
    GET_USUARIO_POR_EMAIL,
    GET_USUARIO_POR_NOMBRE,
    POST_USUARIOS,
    PUT_USUARIOS,
    DELETE_USUARIO,





}
